# Generated by Django 3.0.6 on 2020-05-23 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='descriptipion',
            new_name='description',
        ),
    ]
